"""MC1 §10: byte-exact generated-mandate proof.

governance/mandate.md is generated by concatenating a fixed header with
part1.md (and part2.md when present) in manifest order. The verifier owns the
exact rule — it does NOT trust the manifest's free-form concatenation_rule
string — and proves the relationship from committed blobs at both endpoints.
A mismatch is a hard block; there is never a fall-through to model approval.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "scripts"))

from verifier import generated  # noqa: E402
from verifier.errors import (  # noqa: E402
    GENERATED_DERIVATIVE_MISMATCH,
    BlockingError,
)

ROOT = Path(__file__).resolve().parents[1]
PR23_HEAD = "a9062aa656a5a6f3dbe5991d16ce9c218aad0454"  # pragma: allowlist secret
PR23_BASE = "92552612af6b274be2196f85aeb2ff78efcfe06e"  # pragma: allowlist secret

# Pinned from the frozen commit (test_verifier_generated is the second
# independent witness of these constants).
HEADER_SHA = "4ede45fe4dece3a8d0ae9b6bbcd33d4a30c41f2fa3f85602e3999ea6298f4da1"  # pragma: allowlist secret
COMBINED_SHA = "66b695183852ae03522713e34e2e78f343e3c93ac3b56437441290cbb73d94e6"  # pragma: allowlist secret
PART1_SHA = "e649ea7ccb4f1bd495b9a7ab2e0a40476824a63da3507b6e33d529dcf2f90742"  # pragma: allowlist secret


def _have(sha):
    return subprocess.run(["git", "cat-file", "-e", f"{sha}^{{commit}}"],
                          cwd=ROOT, capture_output=True).returncode == 0


pytestmark = pytest.mark.skipif(not _have(PR23_HEAD),
                                reason="PR23 objects absent")


class TestFixedHeader:
    def test_header_bytes_and_sha_are_pinned(self):
        from verifier.canon import sha256_hex
        assert sha256_hex(generated.FIXED_HEADER) == HEADER_SHA


class TestProofAtHead:
    def test_head_relationship_is_verified(self):
        rel = generated.prove_relationship(PR23_HEAD, cwd=ROOT)
        assert rel["status"] == "GENERATED_VERIFIED"
        assert rel["kind"] == "mandate-concatenation-v1"
        assert rel["expected_generated_sha256"] == COMBINED_SHA
        assert rel["actual_generated_sha256"] == COMBINED_SHA
        assert rel["manifest_combined_sha256"] == COMBINED_SHA
        assert rel["fixed_header_sha256"] == HEADER_SHA
        assert rel["source_sha256_values"] == [PART1_SHA]
        assert rel["generated_path"] == "governance/mandate.md"
        assert len(rel["covered_generated_atom_disposition"]) >= 0
        # the record carries NO raw generated content
        import json
        blob = json.dumps(rel)
        assert "Due-Diligence" not in blob
        assert "relationship_proof_sha256" in rel

    def test_present_at_head_absent_at_base(self):
        endpoint = generated.relationship_at_endpoints(
            PR23_BASE, PR23_HEAD, cwd=ROOT)
        assert endpoint["head"]["status"] == "GENERATED_VERIFIED"
        assert endpoint["base"]["state"] == "absent"


class TestTamperDetection:
    def test_altered_source_mismatch_blocks(self, tmp_path):
        # Build a tiny repo whose manifest points at a part but whose
        # generated file does NOT equal header+part.
        import os
        env = dict(os.environ)
        env.update({"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t",
                    "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@t"})

        def g(*a):
            return subprocess.run(["git", *a], cwd=tmp_path, check=True,
                                  capture_output=True, env=env)
        g("init", "-q", "-b", "main")
        gm = tmp_path / "governance" / "mandate"
        gm.mkdir(parents=True)
        (gm / "part1.md").write_text("PART ONE BODY\n")
        # generated file with WRONG content (missing header)
        (tmp_path / "governance" / "mandate.md").write_text("WRONG\n")
        import hashlib
        p1 = hashlib.sha256(b"PART ONE BODY\n").hexdigest()
        manifest = ('{"catalogue_version":"2.0","parts":['
                    '{"name":"part1","path":"governance/mandate/part1.md",'
                    f'"sha256":"{p1}","tracks":["A"]}}],'
                    '"combined_mandate_sha256":"' + "0" * 64 + '"}')
        (gm / "manifest.json").write_text(manifest)
        g("add", "-A")
        g("commit", "-qm", "tampered")
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=tmp_path,
                              capture_output=True, text=True).stdout.strip()
        with pytest.raises(BlockingError) as e:
            generated.prove_relationship(head, cwd=tmp_path)
        assert e.value.code == GENERATED_DERIVATIVE_MISMATCH

    def test_no_generated_file_is_not_a_relationship(self, tmp_path):
        import os
        env = dict(os.environ)
        env.update({"GIT_AUTHOR_NAME": "t", "GIT_AUTHOR_EMAIL": "t@t",
                    "GIT_COMMITTER_NAME": "t", "GIT_COMMITTER_EMAIL": "t@t"})

        def g(*a):
            return subprocess.run(["git", *a], cwd=tmp_path, check=True,
                                  capture_output=True, env=env)
        g("init", "-q", "-b", "main")
        (tmp_path / "x.txt").write_text("x\n")
        g("add", "-A")
        g("commit", "-qm", "no mandate")
        head = subprocess.run(["git", "rev-parse", "HEAD"], cwd=tmp_path,
                              capture_output=True, text=True).stdout.strip()
        rel = generated.relationship_at_single(head, cwd=tmp_path)
        assert rel["state"] == "absent"
