"""Daily SMS digest: a tiny (<= single-SMS) plain-text regime report.

The body is generated by the LLM (shared model-fallback chain in
app.engine.judgment.run_completion) and hard-capped to a single GSM-7 SMS
(160 chars). If the LLM is unavailable it degrades to a deterministic
template built from the snapshot fields, so the digest always sends.

To stay a SINGLE SMS the body is coerced to GSM-7-safe ASCII: any non-ASCII
character (en-dashes, curly quotes, the euro sign, emoji) would flip the
whole message to UCS-2 and cap it at 70 chars, so those are transliterated
to ASCII before the length cap is applied.

EPISTEMIC GUARDRAIL: the digest is a research signal, never advice — the
"Research, not advice." tag is always present.
"""

from __future__ import annotations

from app.config import get_settings
from app.logging_conf import get_logger
from app.models import Snapshot

log = get_logger(__name__)

_TAG = "Research, not advice."

# Minimal transliteration so a stray Unicode char cannot silently halve the
# SMS length by forcing UCS-2 encoding.
_ASCII_MAP = {
    "–": "-", "—": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "…": "...", " ": " ",
    "≤": "<=", "≥": ">=", "≈": "~", "×": "x",
}

SMS_PROMPT = """You are writing a DAILY TEXT-MESSAGE digest for a research bubble-regime monitor,
for an interested NON-PROFESSIONAL (a retail investor who follows markets
casually) — accessible, but not baby-talk. Ordinary market words are fine
("valuation", "trend", "market breadth", "credit"), but AVOID technical acronyms
and quant jargon (no CAPE, GSADF, LPPLS, VRP, IQR). Write ONE line, at most
{limit} characters, plain ASCII only (no emoji, no dashes other than '-', no
special symbols). Lead with the headline score out of 100 and the action band,
then the single biggest driver in a few plain words. NO probability language, NO
investment advice, NO price targets. Do NOT add quotes. Do NOT append any
disclaimer (one is added automatically).

Readings: score {median}/100, band {band}, rough range {iqr_lo}-{iqr_hi}, warning
flags {flags}/4{override}. Long-term trend: SPY {spy}, QQQ {qqq}. Fragility gauges
S={s}, timing gauges D={d}.
Plain-language note you may draw on: {judgment}
"""


def _asciify(text: str) -> str:
    for uni, repl in _ASCII_MAP.items():
        text = text.replace(uni, repl)
    return text.encode("ascii", "ignore").decode("ascii")


def _clip_to_sms(body: str, limit: int) -> str:
    """ASCII-coerce, collapse whitespace, and hard-cap to `limit` chars."""
    body = " ".join(_asciify(body).split()).strip()
    if len(body) <= limit:
        return body
    # Truncate on a word boundary within the limit, leaving room for an ellipsis.
    cut = body[: limit - 1].rsplit(" ", 1)[0]
    return (cut + ".") if cut else body[:limit]


def deterministic_report(snap: Snapshot, limit: int) -> str:
    """LLM-free fallback digest built purely from snapshot fields."""
    trend = snap.trend_states or {}
    spy = trend.get("SPY", {}).get("faber_10mo", "?")
    qqq = trend.get("QQQ", {}).get("faber_10mo", "?")
    override = " OVERRIDE" if snap.override_fired else ""
    core = (f"bubblegauge {round(snap.median)}/100 {snap.action_band}{override}. "
            f"range {round(snap.iqr_lo)}-{round(snap.iqr_hi)}. "
            f"SPY {spy}, QQQ {qqq}. Flags {snap.red_flag_count}/4.")
    body = f"{core} {_TAG}"
    if len(_asciify(body)) <= limit:
        return _clip_to_sms(body, limit)
    # Too long: drop the tag last, never the score/band.
    return _clip_to_sms(core, limit)


def _block_summary(block: dict, prefix: str) -> str:
    inds = (block or {}).get("indicators", {})
    parts = []
    for k, v in inds.items():
        if not k.startswith(prefix):
            continue
        sub = v.get("sub_score")
        parts.append(f"{k}={sub:.2f}" if isinstance(sub, int | float) else f"{k}=NA")
    return ",".join(parts)


def generate_sms_body(snap: Snapshot) -> tuple[str, bool]:
    """(sms_body, llm_used). Always returns a <= sms_max_len ASCII string.

    Tries the LLM first (shared fallback chain); on any failure falls back to
    the deterministic template so the daily digest always sends."""
    settings = get_settings()
    limit = settings.sms_max_len
    trend = snap.trend_states or {}
    prompt = SMS_PROMPT.format(
        limit=limit - len(_TAG) - 2,  # leave room for the appended disclaimer
        median=round(snap.median), band=snap.action_band,
        iqr_lo=round(snap.iqr_lo), iqr_hi=round(snap.iqr_hi),
        flags=snap.red_flag_count,
        override=" (override fired)" if snap.override_fired else "",
        spy=trend.get("SPY", {}).get("faber_10mo", "?"),
        qqq=trend.get("QQQ", {}).get("faber_10mo", "?"),
        s=_block_summary(snap.block_s, "s"), d=_block_summary(snap.block_d, "d"),
        judgment=(snap.judgment_call or "n/a")[:180],
    )
    try:
        from app.engine.judgment import run_completion

        text = run_completion(prompt).strip().strip('"')
        # Reserve room for the mandatory disclaimer so it can never be
        # truncated away (epistemic guardrail), even if the LLM overruns.
        reserve = max(1, limit - len(_TAG) - 1)
        core = _clip_to_sms(text, reserve)
        if len(core) < 10:  # implausibly short => treat as failure
            raise ValueError("LLM digest too short")
        return f"{core} {_TAG}", True
    except Exception as exc:
        log.warning("sms_report_degraded", error_class=type(exc).__name__, error=repr(exc)[:200])
        return deterministic_report(snap, limit), False
